language: r
cache: packages

env:
  global:
    - secure: "feU+BuzEyvk3i4smXtpd5IR3mZ3ZW2PbYMpEBDsTJ6uLoHvK2s6r+SNNBoD52NHGvqy6I2D1A3XBlzcQbEsx1v5fwyKbQ0UmOZWis75UvATNgni/jpFVvYUUsbDO/a07R5IjWA7wHJXH1WOJyGG3zsF0KY96QPETHEfchViem1/CYA9Z0ND3+7wlrYRJZH3kShQiUcHKUgVTrnnC1dYux/IeaFMMGoDLMnA72CAJHY3SiRqB1gt1iFTxerLQ8uwHrpQ8KX2XhG3sUAkdlAWP08Vy8zjJ84l6QAimNto4TohifSywOXziIACB6sxYIxgDRpIsyeLBJL80/KeRmpJSJOjU8wBVaFkOYTIyvMB1xp7kXecetoUY+iXaXKpB9xsDqQ9riGs3w3H6igBt4OwjU1ldcnSAsQHxfmDWgAq/f4/A2bgh4PatbHr0vzBCXxMbfl6qztH+JmjmvpqTkiXGR7EvSIIzZnflSS6c1uziB1E1vzArSIyfdnduv75s4Az1u5bu96xLpLNiTNMY66r+kvoMreo8J0ofCAojEtNY0WxOGm+iALH3PACY5AGrue84QDUfaAxGRAposz46Tkfc+NcPTbwREOVVdV+wRjVP1fTPg4ygqZzN+K+E60/vVHldgRalHGmzHsKrklU4QsjTzCBd2hET+s3lk7sKLB+r4SY="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
