language: r


before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./_deploy.sh; else echo "PR so not deploying"; fi'

before_install:
- openssl aes-256-cbc -K $encrypted_92e990fc8647_key -iv $encrypted_92e990fc8647_iv
  -in deploy_rsa.enc -out deploy_rsa -d