# Quick Start

## What is the Analytical Platform?

The Platform provides four main services to analysts:

- Access to analytical software.
- Data storage and access to datasets.
- The ability to create and share interactive data products and websites.
- Collaboration tools for analysts that enable teams to work concurrently on complex analytical projects, and perform QA incrementally.



### High level diagram of the platform:


```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
cat(readLines('resources/svg/platform.svg'), sep = '')
```


## Why should I use the Analytical Platform?

The Platform provides a number of advantages over existing analytical infrastructure:

- It provides access to the latest versions of modern analytical software, such as R Studio,
- It provides more powerful computational resources (>10Gb RAM and fast CPUs) than DOM1 machines.
- It can be accessed from multiple computer systems - DOM1, Quantum (HMPPS's system), and MacBooks. 
- It allows analysts to securely deploy data products such as R Shiny applications and web sites, including web-base data visualisations.
- The platform is hosted in the cloud, which means it is scalable and easy to access remotely. Data storage is unlimited, and computational resource can be scaled to demand.

##  FAQ: How do I?

This section covers common tasks you may want to complete on the platform. If we've missed something, let us know.

##### Get access to the platform{-}

See [Getting Started][Getting Started].

##### Share data or code with a team{-}

If you haven't set up a team yet, see [User Administration][User Administration].
If you've got a team but want to upload data see [Uploading data to S3][Uploading data to S3].
If you want to share code see guidance on [Github][Configuring Git and Github for use on the Analytical Platform].

##### Upload and work with data{-}

If the data isn't shared, and is less than 100 MB, you can upload it directly to R Studio. See 'uploading files' [here](https://support.rstudio.com/hc/en-us/articles/200713893-Uploading-and-Downloading-Files).

If you want to share the data, or if it's more than 100 MB, you'll need to [set up a team][User Administration], then upload data (see [Uploading data to S3][Uploading data to S3] ).

To import data from S3 into R for analysis, see [Importing data from S3 into R][Importing data from S3 into R].

##### Make an interactive dashboard and deploy it securely{-}

See [Deploying a Shiny App ][Deploying a Shiny App ].


## Contacting us

For quick support, contact us on the `#analytical_platform` [Slack channel](https://asdslack.slack.com/messages/anaytical_platform/). Alternatively, contact us by [email](mailto:robin.linacre@digital.justice.gov.uk)
