# Common Errors and Sollutions 

## Failed to lock directory

This error is typically encountered after a failed package install. 

**Error**
```
ERROR: failed to lock directory ‘/home/robinl/R/library’ for modifying
Try removing ‘/home/robinl/R/library/00LOCK-readr’
```

**Solution**

Run the following:
```r
install.packages('pacman')
pacman::p_unlock()
```

If that does not work, or if you have trouble installing the `pacman` package, try the following:

>Go to 
>Tools -> Shell
>and type:
>
>`rm -rf /home/robinl/R/library/00LOCK-readr`
>
>See [here](http://linuxcommand.org/man_pages/rm1.html) for more details.  Be careful with the `rm` command!

## Platform two factor authentication failing

If the clock on your phone is inaccurate, then the two factor authentication codes it produces may be out of sync, and therefore not work.

**Solution**

Ensure that your phone's clock is up to date.  Most phones will sync time automatically with an internet time server, but if you don't have internet access, you can update the clock manually.  Try and make sure it's in sync with your DOM1 clock.


## Unable to access data using `aws.s3` package.

Unfortuntely `aws.s3` does not support the granular file access permission model we are using on the platform.  Specifically, it is unable to automatically provide the user with the right file access credentials.  We provide `s3tools` as a solution to this problem, which manages your credentials for you.

We recommend that, where possible, users should use `s3tools`.  Where this is not possible, include a call to `s3tools::get_credentials()` prior to making the call to `aws.s3`, and this will guarantee that fresh credentials are generated before your call to `aws.s3`

## `s3tools::s3_path_to_full_df() fails on Excel file

`s3tools::s3_path_to_full_df` attempts to read in data from various filetypes, including Excel, but this sometimes fails.

If it does, you have two options:

#### Option 1:  Use s3tools::read_using()

This allows you to specify what function you want to use to attempt to read the file. So, for example you can do: 
`s3tools::read_using(openxlsx::readWorkbook, path = "alpha-everyone/my_excel.xlsx")` to attempt to read the file `alpha-everyone/my_excel.xlsx` using `openxlsx::readWorkbook`

#### Option 2:  Save the file to your project directory and load it from there, rather than from S3

`aws.s3::save_object("my_excel.xlsx", "alpha-everyone", "file_name_to_save_to_in_home_directory.xlsx")`

and then read it in using e.g.

`openxlsx::readWorkbook("file_name_to_save_to_in_home_directory.xlsx")`

